### PR TITLE
Introduce container

### PR DESCRIPTION
**Pull request by chemelli74**
Add `devcontainer` to the repo for easy creation of dev environment

### CODE REVIEW

**Comment by rstrouse** [comment]
There is only one problem with this.  It destroys my external mounts.   I have more than one editor and I also have more than one project.  Any ideas on how to make this happen without pinning the environment.  I looked at custom builds but that is a goat rope.

**Comment by chemelli74** [comment]
> There is only one problem with this. It destroys my external mounts. I have more than one editor and I also have more than one project. Any ideas on how to make this happen without pinning the environment. I looked at custom builds but that is a goat rope.

What if we discuss a bit of this and the others proposal on [Discord](https://discord.com/invite/home-assistant) ?
You can contact me with `chemelli74#2180`

Simone

**Comment by chemelli74** [comment]
@rstrouse any time to discuss about this ?

**Comment by chemelli74** [comment]
Hi,

I asked to discuss in discord, because I though it would be easier that here, nvm.
`DevContainer.json` is supposed to create a common environment for the project so that all devs have the same environment.
You can easily add vscode common settings:

image

Also, is not mandatory to use it, the repo can still be opened/cloned as a normal non-container repo.

So I miss the reason why this should not work for you.

**Comment by rstrouse** [comment]
From everything I have tried the devcontainer.json file is the only place where I can mount directory sources from around my network.  The problem with it is that when you include that file in the .devcontainer it will contaminate (overwrite) my configuration but I may have some tricks up my sleeve.   

Perhaps I can store and mount that file so that it never gets included in my environment by shadowing it for my local HA dev environment or get creative with the storage location for my devcontainer.json.  I'll try out some things this weekend to see if I can preserve my hybrid environment.  It will just mean maintaining that file separately.

**Comment by rstrouse** [comment]
I moved around my mounts so that the devcontainer.json doesn't interfere with my setup.

**Pull request merged**
